### ISSUE TITLE
Card/Effect system

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#17] opened 2018-02-28 16:11 UTC
From the requirements extension for assessment 4 we decided to implement a card system. The _cards_ are either a **bonus** or  a **punishment**.

How cards are dealt
-
>**TBD**

Bonus cards
-
>**TBD**

Punishment cards
-
>**TBD**

**Comment by Gorea235** [comment] 2018-03-01 00:09
The way the card system will work is that each card will apply an effect to a Unit, Player or Sector. This way we can have things like the 'graduate' effect (undergrad -> postgrad), action limiter effect (e.g. you apply the effect to an enemy and they have e.g. 1 less action on their next turn (or few turns)), and traps card (e.g. enemy unit land on a sector, they take damage or have level reduced).

**Comment by Nicodaw** [comment] 2018-03-01 15:13
The temporary versions for Bonus Attack/Defence may be burn-like card. So you play a card that deals damage (reduces level) to one enemy unit you select, or increases the level of one friendly unit you select. I know this is very similar to Drop enemy level, but its going to work and we don't have to implement an entirely different attack system (pls lets not)

I suggest we have a single post-grad upgrade type, which lets say increases the selected unit's level cap to 10 and has movement range boost on his own tiles

An additional trap version may be to block a sector from anyone standing on it for N number of turns ?

I am not sure about the global attack and defence apart from the usual _increase attack and defence bonuses on the player_. Maybe do that for a set amount of turns ?

**Comment by Gorea235** [comment] 2018-03-01 19:25
Since the card system will mostly be driven via the effect system, I've renamed the issue to be both. The current idea on how the effect system will work is as follows:

- Effects
  - There will be a single abstract class (called `Effect`) that will be the base of all effects in the game
    - Each effect will be a implementation on top of this class
    - All properties and alterations that each effect can set/do will be specified in this class
      - This does mean that effects might have a lot of redundant properties, but making the effects come from a single base allows for a much more powerful system
  - Each effect will have a 'selection' function (specified as abstract in the base class)
    - When working out where a card can be applied, this function will be given the players and sectors currently in the game, and return an object containing lists of the players, units, and sectors that it can be applied to
    - The result will then be used to highlight the players/units/sectors that the effect can be applied to (when seeing where a card can be applied to)
  - The base class will provide an `ApplyTo` method that will make the effect apply itself to the given player/unit/sector
    - This function will then work out which one was given, and call the relevant `ApplyToXXX` function
    - By default, the implementations of these specific 'apply to' functions will throw something like `InvalidOperationException`
    - Implementing classes will override these functions and add their own initialization code that they need to run on the given item (allowing for things like postgrad upgrading)
    - Few effects will need to actually store/use the object that is given during the `ApplyTo` system, however by adding it, it means effects can do a lot without sacrificing generalisation
  - Effects will receive events from the main system
    - These might include, but are not limited to: Turn start, turn end, unit attack, unit attacked, unit spawn, unit death, player stat change (maybe?), sector ownership change, player elimination, effect removal (important)
  - A 'remove' function will be needed (to allow effects to end without needing to have some sort of global effect management)
    - (see below for more on this)
- Effect Manager
  - Each sector, player and unit will have an `EffectManager`
  - This will be used to manage all applied effect
    - This includes combining all bonuses (e.g. multiple attack bonuses), effect adding, effect event processing, effect removal
  - Effects will be given a reference to this manager, and the manager will have a reference to the object is is linked to
    - While having this kind of 'back-and-forth' referencing might be detrimental to code manageability, it is required for Effects to apply certain effects to the object (e.g. postgrad effect), and to be able to remove themselves
  - By having this kind of manager system, effects can organise themselves without having to add large amounts of complex management elsewhere (e.g. directly in sector/player/unit)
  - The effect manager can also dynamically work out the bonuses and results of all the currently applied effects (e.g. multiple attack increase and multipliers can be worked out when the `AttackBonus` property is called)
    - This would require *some* duplication on properties, however the dynamic aspect means that effects will not need to permanently alter the object it's applied to, and allows them to be agnostic to what it's actually applied to (e.g. if the effect altered the bonus attack directly, it would need to account for player or unit bonus attack, while not attempting to do so on sectors (unless we allow sectors to provide extra bonuses to occupying units))
  - This class can provide `ApplyEffect` and `RemoveEffect` methods that allow it to add/remove effects when needed
    - These methods can have overloads that allow adding and removing effects in multiple ways, such as by class type (e.g. `RemoveEffect<PvcEffect>()` would remove all effects of type `PvcEffect` from the `EffectManager`, or `RemoveEffect()` could remove all effects)
  - The effect manager can also handle the applied effect IDs, which would be used for referencing a certain applied effect directly (which would allow direct removal of a given effect, which would be needed by `Effect` in order to remove itself)

This may seem like a lot (it is), but it is a very detailed description on the actual implementation, which means that a lot of it could be directly transferred to actual code (which is why it's a bit long).

**Comment by Nicodaw** [comment] 2018-03-01 19:28
For the activation of cards I was thinking precisely that a card should be played only during a particular player's turn but also consume one action (to bring some balance).

**Comment by Gorea235** [comment] 2018-03-01 19:30
I think consuming an action might be a bit much, especially since it is already *very* limiting on unit movement.

**Comment by Gorea235** [comment] 2018-03-16 01:33
The main effect system is now implemented. It will be used at the main method by which stats are stored and calculated for players, sectors and units. Now that it implemented, I will start to work on incorporating it into to main code (such as using a `PvcEffect` class to handle the allocation of the PVC, rather than using a boolean value).

Now we have this system, we will use it as the main driving force for 'applied' logic, where logic is only applied to certain objects, as it makes managing this applied logic more easier and modifiable.

**Comment by Gorea235** [comment] 2018-03-17 02:01
We are at the stage where the effect system is done I think, meaning that all was have left are the actual cards and the card system. This means we now need to come up with a list of cards that would could implement, and how to implement the card system.

**Comment by Nicodaw** [comment] 2018-03-19 09:02
Card effects can be discussed [here](https://docs.google.com/document/d/1P3KmSPJASBZ0yS3TSXYKaup1JtJnm4PvBVuDSGwMpx0/edit).

For the card implementation: we did mention the possibility of instead of att/def bonus from the minigame to just get cards. Probably not a one:one mapping, because currently the max points from the minigame are 10, which is too OP. _For every two coins you collect, you get a random card_ seems to work?

**Comment by Nicodaw** [comment] 2018-03-29 14:59
[Sample card layout ](https://puu.sh/zRXNa/1e637499b4.png). The _TYPE_ is what it can target as described in [the card list](https://docs.google.com/document/d/1P3KmSPJASBZ0yS3TSXYKaup1JtJnm4PvBVuDSGwMpx0/edit). 
Currently they are targeting [(from left to right)](https://puu.sh/zRWVo/40feea8a36.png) a single friendly unit, a single enemy unit, all player's units, an enemy player's units and sectors.

We have to either very succinctly describe the effects in text or possibly use image descriptions (for example, the Graduate card's effect can be just [👨 - > 👨‍🎓])

The image will be mainly for flavour so if we can't fit them, we can just remove the section. Function-wise the only thing we need is the effect + target and the name for some form of identification. The images would be nice though.

**Comment by Gorea235** [comment] 2018-03-29 15:26
I've thought of some possible effect styles. The first one would be an effect that is applied permanently to a sector (or for a number of turns), and whoever controls the sector can get an attack or defence bonus (like a more powerful temp landmark). We would have to alter how attack and defence scores are fetched (i.e. we would need to iterate over all owned sectors and add up each of their attack and defence values), but it wouldn't be difficult to add.

Another one would a sacrificial one, where you have the first card that can only be applied to, lets say, an owned unit, and it destroys it. However, the result of this, is that you get given another card that has a more powerful than normal effect (similar to Yu-Gi-Oh with sacrifice summoning). Using multiple cards for this would work with how the system is designed, and might actually make for a better system to use in the end.

**Comment by Gorea235** [comment] 2018-04-18 13:28
I've decided on the structure for the card system. It will be split in 2, logical and UI.

The logic side consists of the `CardFactory` class, `CardType` enum, and all the `Effect` implementations. What needs to be done for this section is the following:

- All cards need a relevant Effect implementation
  - This doesn't have to be 1-1, if 2 cards do almost the same thing but with slightly different intensities, then the effect implementation can just have the values given by the constructor, and the factory class set them (or something along that line)
    - Instead of passing the values into the constructor, you could have 'modes' which change which values the effect expresses (so the actual possible values are all in the class), and the mode is passed in by the constructor
- Each card needs a corresponding `CardType` enum
  - This *is* 1-1, since it's how we refer to each card when creating them

The UI side consists of only `CardManager` and `CardController`, however they will be more complicated to implement. They need:

- A way to store all the cards a player has in a 'list-like' way
- The ability to add, sort and remove cards
  - Removal needs to be done by the exact card reference, so when a card is used that `CardController` is removed from the list, and only that
- The classes together will manage all of the animations needed for the cards
- The card details will be entirely given by the effect it is driven by
  - This means all the details the card needs will need to be specified and then added to the `Effect` class

In terms of workload, if people want to help, they can plan out and write up `Effect` implementations for each card, since it is just writing each implementation in turn, rather than any complex code. The UI side will be difficult to split between people, so I will focus on that for now while people write up the card effect implementations.

**Comment by Gorea235** [comment] 2018-05-01 12:40
The card system is now implemented, so now it's a case of cleaning things up and making sure all the effects work as intended. This also means we need to work on some of the other enhancement issues, since things like unit range and player actions aren't supported yet.

**Comment by Gorea235** [comment] 2018-05-01 23:53
All the effects have been gone through and implemented properly, so the only thing that might be left are bugs we may find. This means that the whole card & effect system is done.

**Closed by Gorea235** 2018-05-01 23:53 UTC
Labels: feature
